name: Test, Build and Deploy App and Server
on: push
permissions:
  contents: write

jobs:
  test-app:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: echo 'No Tests Yet!'
  
  build-app:
    name: Install and Build App
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build -p android --profile preview --non-interactive
  
  build-server:
    name: Build and Deploy Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        project_id: recipe-396801
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure docker for GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        push: true
        tags: gcr.io/recipe-396801/server:latest
        build-args: |
          HTTP_PORT=8080
    

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        image: gcr.io/recipe-396801/server:latest
        service: recipe-api
        env_vars: |
            MDB_USERNAME=${{ secrets.MDB_USERNAME }}
            MDB_PASSWORD=${{ secrets.MDB_PASSWORD }}
            GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD}}